var m = require('mithril');
var chessground = require('chessground');
var progress = require('./progress');
var score = require('./score');
var breakbar = require('./breakbar');
var generate = require('../../../generate/src/generate');

function visualBoard(ctrl) {
  return m('div.lichess_board', m('div.lichess_board_wrap', m('div.lichess_board', [
    chessground.view(ctrl.ground)
  ])));
}

function info(ctrl) {
  return [m('div.explanation', [
      m('br'),
      m('br'),
      m('p.center', {
        style: {
          textAlign: 'center'
        }
      }, 'Training mode'),
      m('br'),
      m('br'),
      generate.featureMap.map(f => {
        return m('div.button.newgame', {
          title: f.fullDescription,
          onclick: function() {
            ctrl.selection(f.description);
            ctrl.newGame();
          }
        }, f.description);
      }),
    ]),
    m('br'),
    m('br'),
    m('p.center', {
        style: {
          textAlign: 'center'
        }
      }, 'Post your high scores on ',
      m("a.hiscore.external[href='https://en.lichess.org/forum/game-analysis/forking-hell-challenge']", {
        style: {
          color: "#55a"
        }
      }, 'lichess.')),
    m('br'),
    m('br'),
    m('p.center',m('div.button.newgame', {
      onclick: function() {
        ctrl.blindfold();
      }
    }, 'Blindfold bonus'))

  ];
}

module.exports = function(ctrl) {
  return [
    m("div.#site_header",
      m('div.board_left', [
        m('h2.center',
          m('a#site_title', {
              onclick: function() {
                window.open("./index.html?fen=" + encodeURI(ctrl.fen()));
              }
            }, 'feature',
            m('span.extension', 'tron'))),
        m('br'),
        progress(ctrl)
      ])
    ),
    m('div.#lichess',
      m('div.analyse.cg-512', [
        m('div',
          m('div.lichess_game', [
            visualBoard(ctrl),
            m('div.lichess_ground', info(ctrl))
          ])
        ),
        m('div.underboard', [
          m('div.center', [
            breakbar(ctrl),
            m('br'),
            score(ctrl),
            m('br'),
            m('br'),
            m('small', 'Data autogenerated from games on ', m("a.external[href='http://lichess.org']", 'lichess.org.')),
            m('small', [
              'Uses libraries ', m("a.external[href='https://github.com/ornicar/chessground']", 'chessground'),
              ' and ', m("a.external[href='https://github.com/jhlywa/chess.js']", 'chessjs.'),
              ' Source code on ', m("a.external[href='https://github.com/tailuge/chess-o-tron']", 'GitHub.')
            ])
          ])
        ])
      ])
    )
  ];
};
